spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/instagram
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      location:

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


