spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/instagram
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      location:

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: goldking
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
